"""initial schema

Revision ID: 952b780fdc15
Revises: 
Create Date: 2026-06-26 01:58:39.824745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952b780fdc15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reddit_post_id', sa.Text(), nullable=False),
    sa.Column('reddit_comment_id', sa.Text(), nullable=True),
    sa.Column('subreddit', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('author_account_age_days', sa.Integer(), nullable=True),
    sa.Column('author_karma', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('extracted_name', sa.Text(), nullable=False),
    sa.Column('resolved_place_id', sa.Text(), nullable=True),
    sa.Column('resolution_confidence', sa.Float(), nullable=True),
    sa.Column('needs_manual_review', sa.Boolean(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_shill_suspected', sa.Boolean(), nullable=True),
    sa.Column('posted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_post_id', 'reddit_comment_id', 'extracted_name')
    )
    op.create_table('places',
    sa.Column('place_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Double(), nullable=False),
    sa.Column('lng', sa.Double(), nullable=False),
    sa.Column('cuisine_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('price_level', sa.SmallInteger(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('google_rating', sa.Float(), nullable=True),
    sa.Column('google_ratings_count', sa.Integer(), nullable=True),
    sa.Column('is_sponsored', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata_cached_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('resolution_cache',
    sa.Column('extracted_name_normalized', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('resolved_place_id', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('extracted_name_normalized', 'city')
    )
    op.create_table('scores',
    sa.Column('place_id', sa.Text(), nullable=False),
    sa.Column('reddit_mention_count', sa.Integer(), nullable=False),
    sa.Column('reddit_sentiment_avg', sa.Float(), nullable=False),
    sa.Column('commenter_trust_score', sa.Float(), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=False),
    sa.Column('longevity_score', sa.Float(), nullable=False),
    sa.Column('sponsored_penalty', sa.Float(), nullable=False),
    sa.Column('local_trust_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('resolution_cache')
    op.drop_table('places')
    op.drop_table('mentions')
    # ### end Alembic commands ###
